// Prijevodi (hr/en) — samo podaci, bez stanja.
//
// Zašto odvojeno od `i18n.svelte.js`: rune (`$state`) se ne mogu uvesti u Node,
// a ovako `scripts/check-i18n.mjs` provjerava da oba jezika imaju iste ključeve.

export const hr = {
  app: 'Rustiio',
  nav: { dashboard: 'Pregled', library: 'Knjižnica', devices: 'Uređaji', settings: 'Postavke', logs: 'Zapisnik' },
  field: {
    changed_unsaved: 'Promijenjeno, još nije spremljeno',
    on: 'uključeno',
    off: 'isključeno',
    all_cores: 'sve jezgre',
    cores_word: 'jezgri',
    all: 'Sve',
    auto: 'Automatski',
    unavailable: 'nije dostupno',
    absolute_hint: 'Putanja mora početi s „/“',
    browse: 'Pretraži mape na serveru',
    add_row: 'Dodaj redak ručno',
    type_path: 'Upiši putanju ručno',
    tag_add: 'dodaj…',
    root_label: 'naziv',
    choose: 'Odaberi',
    remove_root: 'Ukloni mapu',
    add_folder: 'Dodaj mapu s videom',
  },
  card: {
    collapse: 'Skupljeno / rašireno',
    width: 'Širina kartice',
    width_hint: 'Povuci za širinu (ili strelice lijevo/desno)',
  },
  err: {
    status: 'Dohvat stanja nije uspio',
    streams: 'Dohvat strimova nije uspio',
    stats: 'Dohvat statistike nije uspio',
    devices: 'Dohvat uređaja nije uspio',
    library: 'Dohvat knjižnice nije uspio',
    profiles: 'Dohvat profila nije uspio',
    rescan: 'Skeniranje nije uspjelo',
    posters: 'Dohvat postera nije uspio',
    logs: 'Dohvat zapisnika nije uspio',
    restart: 'Restart nije uspio',
    server_down: 'Server ne odgovara — čekam da se vrati…',
    server_back: 'Server je ponovno dostupan',
    restart_timeout: 'Servis se nije digao u 90 sekundi — pogledaj zapisnik',
  },
  common: {
    remove: 'Ukloni',
    refresh: 'Osvježi',
    save: 'Spremi',
    saved: 'Spremljeno',
    scan: 'Skeniranje',
    started: 'pokrenuto',
    posters: 'Posteri',
    cancel: 'Odustani',
    search: 'Traži',
    all: 'Sve',
    video: 'Video',
    audio: 'Glazba',
    image: 'Slike',
    folder: 'Mapa',
    loading: 'Učitavam…',
    error: 'Greška',
    none: 'Nema podataka',
    copy: 'Kopiraj',
    copied: 'Kopirano',
    export: 'Izvezi',
    reset: 'Vrati početno',
    language: 'Jezik',
    uptime: 'Radi',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    days: 'd',
  },
  dashboard: {
    title: 'Pregled',
    streams: 'Aktivni streamovi',
    library: 'Knjižnica',
    system: 'Računalo',
    disks: 'Diskovi',
    logs: 'Zapisnik',
    posters: 'Posteri',
    transcode: 'Transcode',
    direct: 'Izravno',
    cpu: 'CPU',
    memory: 'RAM',
    gpu: 'GPU',
    load: 'Opterećenje',
    items: 'objekata',
    roots: 'mapa',
    subscriptions: 'TV-a pretplaćeno',
    no_streams: 'Nitko trenutno ne gleda.',
    transcodes: 'transcode',
    free: 'slobodno',
    of: 'od',
    slots: 'slobodnih mjesta',
    poster_pending: 'čeka poster',
    have_poster: 'imaju poster',
    no_poster: 'bez postera',
    cores: 'jezgre',
    on: 'uključen',
    off: 'isključen',
    tmdb_key: 'TMDB ključ',
    no_key: 'bez ključa',
  },
  library: {
    title: 'Knjižnica',
    search_placeholder: 'Traži naslov…',
    empty: 'Nema objekata u ovoj mapi.',
    play: 'Pusti',
    copy_link: 'Kopiraj link',
    on_tv: 'Pusti na TV',
    on_tv_later: 'Pusti na TV dolazi u Fazi 6',
    open_folder: 'Otvori mapu',
    items_count: 'objekata',
    no_poster: 'bez postera',
    filter_kind: 'Vrsta',
    size: 'Veličina',
    subtitles: 'Titlovi',
    added: 'Dodano',
    rules: 'pravila',
  },
  hw: {
    title: 'Stroj na kojem radi',
    cpu: 'Procesor',
    gpu: 'Grafička',
    no_gpu: 'nema grafičkog ubrzanja — transcode ide na procesoru',
    encoders: 'Enkoderi',
    recommended: 'Preporučeno',
    subtitles_yes: 'titlovi urezivanjem rade',
    subtitles_no: 'nema urezivanja titlova',
    cores: 'jezgre',
    threads: 'niti',
  },

  devices: {
    title: 'Uređaji',
    none: 'Još se nitko nije javio. Uključi TV ili VLC i osvježi.',
    name: 'Uređaj',
    user_agent: 'User-Agent',
    seen: 'Zadnji put',
    profile: 'Profil',
    requests: 'Zahtjeva',
    headers: 'DLNA zaglavlja',
    profiles_title: 'Profili uređaja',
    generic: 'općenito',
    dlna_client: 'DLNA klijent',
    hint: 'Prvi put se uređaj sam javi — odabere mu se profil, a ti mu možeš napraviti svoj',
    make_profile: 'Napravi profil',
    make_profile_hint: 'Stvori vlastiti profil za ovaj uređaj iz njegovih DLNA zaglavlja (TOML u mapu profila)',
    toml_hint: 'Prikaži zaglavlja uređaja i TOML koji bi se spremio',
    saved: 'Profil spremljen',
    chosen: 'izabrano',
    profile_auto: 'automatski',
    assign_hint: 'Koji profil ovaj uređaj koristi (automatski = prepoznavanje po User-Agentu)',
    rules_title: 'Pravila profila',
    rules_note: 'Ova pravila odlučuju pušta li se zapis direktno ili ide u transcode. Dubina boje je ono što 10-bit HEVC šalje u transcode.',
    pick_profile: 'Profil',
    containers: 'Kontejneri',
    video_codecs: 'Video kodeci',
    audio_codecs: 'Audio kodeci',
    max_width: 'Najveća širina',
    max_height: 'Najveća visina',
    bit_depth: 'Dubina boje (bitova)',
    max_bitrate: 'Najveći bitrate (kb/s)',
    max_channels: 'Najviše kanala',
    target: 'U što se prekodira',
    target_video: 'Video kodek',
    target_audio: 'Audio kodek',
    target_container: 'Kontejner',
    target_bitrate: 'Bitrate (kb/s)',
    save_rules: 'Spremi pravila',
    saved_rules: 'Pravila profila spremljena',
    reset_rules: 'Vrati na ugrađeno',
    reset_done: 'Profil vraćen na ugrađena pravila',
    list_hint: 'Popis odvojen zarezom',
    keep_small: 'Kod prekodiranja',
    rules_hint: 'Koliko se pravila profila poklapa s prijavljenim uređajima',
    delete: 'Izbriši',
    delete_confirm: 'Sigurno?',
    delete_hint: 'Briše datoteku profila; uređaji koji su ga koristili vraćaju se na automatski izbor',
    deleted: 'Profil izbrisan',
    devices_cleared: 'uređaja vraćeno na automatski',
    user_profile: 'moj profil',
    modified: 'izmijenjen',
    edit_profile: 'Uredi pravila',
    confirm_delete: 'Izbrisati profil?',
    confirm_hint: 'Briše se datoteka profila. Uređaji koji su ga koristili ostaju bez izabranog profila — poslije im odaberi drugi.',
    delete_device: 'Izbrisati uređaj?',
    delete_device_hint: 'Uređaj se briše iz popisa. Ako se ponovno javi, vratit će se sam.',
    device_deleted: 'Uređaj izbrisan',
    device_delete_failed: 'Brisanje uređaja nije uspjelo',
    cancel: 'Odustani',
    left_without: 'uređaja bez profila — odaberi im novi',
    no_profile: 'nema profila',
    profile_name: 'Ime profila',
    target_channels: 'Kanala u transcodeu',
    target_height: 'Visina transcodea (px)',
    target_remux: 'Dopusti remux (bez ponovnog kodiranja)',
    subtitles_mode: 'Titlovi',
    subtitles_formats: 'Formati titlova',
    sub_soft: 'Uređaj ih učita sam (soft)',
    sub_burn: 'Ureži u sliku (burn)',
    sub_none: 'Uređaj ne prikazuje titlove',
    dlna_title: 'DLNA sitnice',
    dlna_op: 'DLNA.ORG_OP',
    dlna_flags: 'DLNA.ORG_FLAGS',
    dlna_pn: 'Šalji DLNA.ORG_PN',
    dlna_time_seek: 'TimeSeekRange umjesto Range',
    rules_match: 'Prepoznavanje uređaja',
    rule_ua: 'User-Agent sadrži',
    rule_name: 'Naziv uređaja sadrži',
    rule_type: 'Tip uređaja',
    rule_ip: 'IP adrese',
    new_profile: 'Sačuvaj kao novi profil',
    new_profile_ph: 'npr. Samsung dnevna soba',
    new_needs_name: 'Upiši ime novog profila',
    profile_created: 'Novi profil',
  },
  settings: {
    title: 'Postavke',
    server: 'Server',
    friendly_name: 'Ime na TV-u',
    bind: 'Adresa',
    port: 'Port',
    advertise_ip: 'IP za oglašavanje',
    udn: 'UDN (identitet)',
    library: 'Biblioteka',
    roots: 'Mape',
    add_root: 'Dodaj mapu',
    path: 'Putanja',
    label: 'Naziv',
    kind: 'Vrsta',
    transcode: 'Transcode',
    enabled: 'Uključen',
    ffmpeg: 'ffmpeg',
    ffprobe: 'ffprobe',
    max_concurrent: 'Najviše paralelno',
    network: 'Mreža',
    ip_family: 'Obitelj IP-a',
    ui: 'Sučelje',
    file: 'Datoteka configa',
    restart_needed: 'Za ove promjene treba restart servisa',
    restart_now: 'Restartaj servis',
    restart_confirm: 'Prekinut će se aktivni streamovi. Restartati?',
    restarting: 'Servis se diže…',
    unchanged: 'Nema promjena',
  },
  logs: {
    title: 'Zapisnik',
    live: 'Živo',
    paused: 'Pauzirano',
    paused_hint: 'Prikaz je zaustavljen, linije se i dalje skupljaju.',
    level: 'Razina',
    clear: 'Očisti prikaz',
    download: 'Preuzmi',
    connected: 'Spojen',
    disconnected: 'Veza prekinuta',
    kept: 'zadržano',
    filter: 'Filtar',
  },
  health: { ok: 'Radi', bad: 'Ne radi' },
  // Tekstovi iz komponenti (`t('ns.kljuc')`). Isti engleski tekst = isti ključ.
  app: {
    connected: 'spojeno',
    every_setting_saved_to_config_toml: 'Sva podešavanja, spremaju se u config.toml',
    live_server_log_with_levels_and_filtering: 'Zapisnik servera u živo, s razinama i filtriranjem',
    live_state_of_the_server_library_and_strea: 'Stanje servera, knjižnice i strimova u živo',
    no_log_stream: 'nema toka',
    tvs_that_appeared_and_the_profile_each_one: 'Televizori koji su se pojavili i profil koji svaki dobiva',
    what_the_tvs_see_folder_by_folder: 'Ono što televizori vide, mapa po mapa',
  },
  dash: {
    acceleration: 'Ubrzanje',
    active_streams: 'Aktivni strimovi',
    add_video_folder: 'Dodaj mapu s videom',
    all_devices: 'Svi uređaji',
    available_encoders: 'Dostupni enkoderi',
    check_now: 'Provjeri sada',
    concurrent_limit: 'Istovremeno najviše',
    cores: 'jezgre',
    coverage: 'pokrivenosti',
    cpu: 'Procesor',
    cpu_last_minutes: 'Procesor — zadnjih minuta',
    devices: 'Uređaji',
    direct: 'Izravno',
    discovery_and_subscriptions: 'Oglasi i pretplate',
    disks: 'Diskovi',
    folders: 'mapa',
    folders_saved_a_restart_is_needed: 'Mape spremljene. Za promjenu treba ponovno pokretanje.',
    folders_saved_a_restart_is_needed_reopen_t: 'Mape spremljene. Za novu mapu treba ponovno pokretanje: u aplikaciji zatvori i otvori Rustiio, na serveru restartaj uslugu.',
    free: 'slobodno',
    free_slots: 'Slobodnih mjesta',
    full_log: 'Cijeli zapisnik',
    have: 'imaju',
    items: 'objekata',
    library: 'Knjižnica',
    live: 'uživo',
    load: 'opterećenje',
    log: 'Zapisnik',
    machine: 'Računalo',
    memory: 'Memorija',
    memory_last_minutes: 'Memorija — zadnjih minuta',
    metadata_probed: 'Metapodaci izmjereni',
    missing: 'nema mape',
    no_device_has_connected_yet: 'Još se nijedan uređaj nije javio.',
    no_disk_data: 'Nema podataka o diskovima.',
    no_folder_configured: 'Nijedna mapa nije zadana.',
    no_key: 'bez ključa',
    no_tv_is_playing_right_now: 'Nijedan televizor trenutačno ne gleda.',
    none: 'nema',
    off: 'isključene',
    off_2: 'isključeno',
    offline: 'prekinuto',
    on: 'uključene',
    on_2: 'uključeno',
    posters: 'Naslovnice',
    remove_a_folder_that_is_gone: 'Ukloni mapu koje nema na disku',
    requests: 'zahtjeva',
    reset_card_layout: 'Vrati raspored kartica',
    running_now: 'U tijeku',
    saving: 'spremam…',
    show_listing: 'Prikaži popis',
    subscriptions: 'pretplata',
    the_log_is_empty: 'Zapisnik je prazan.',
    titles: 'naslova',
    transcode: 'Prekodira',
    transcoding: 'Prekodiranje',
    uptime: 'Radi neprekidno',
    video: 'video',
    virtual_folders: 'Virtualne mape',
    waiting: 'čeka',
  },
  set: {
    advanced: 'Napredno',
    all_saved: 'sve spremljeno',
    apply: 'Primijeni',
    cannot_read_settings: 'Ne mogu pročitati postavke',
    config_parsed_from_json_review_and_save: 'Config pročitan iz JSON-a — provjeri i spremi.',
    error: 'Greška',
    hide: 'Sakrij',
    invalid_json: 'JSON nije ispravan',
    not_saved: 'Nije spremljeno',
    restart_pending: 'čeka restart',
    restart_pending_2: 'restart čeka',
    restart_service: 'Restartaj servis',
    restart_the_service_now_streams_will_drop: 'Restartati servis sada? Strimovi će se prekinuti.',
    revert: 'Vrati',
    save_settings: 'Spremi postavke',
    saving: 'Spremam…',
    service_is_coming_back_page_will_reload: 'Servis se diže… stranica će se osvježiti.',
    settings_sections: 'Sekcije postavki',
    show: 'Prikaži',
    some_fields_apply_only_after_a_service_res: 'Neka polja vrijede tek nakon restarta servisa.',
    the_whole_config_as_json_use_it_for_anythi: 'Cijeli config kao JSON. Koristi kad nešto nije u obrascu — i za kopiranje postavki na drugi server.',
    these_fields_are_saved_but_take_effect_onl: 'Ova polja su spremljena, ali vrijede tek kad se servis digne:',
  },
  side: {
    items: 'stavki',
    live_log_connected: 'živi zapisnik spojen',
    log_disconnected: 'zapisnik nije spojen',
  },
  tr: {
    scan_title: 'Sken sustava i automatsko podešavanje',
    scan_help: 'Provjeri što stroj ima (ffmpeg, procesor, grafička) i izmjeri stvarnu brzinu svakog enkodera. Preporuka se temelji na mjerenju, ne na pretpostavci.',
    scan_button: 'Skeniraj sustav',
    scanning: 'Skeniram…',
    scan_hint: 'Pritisni „Skeniraj sustav" — traje nekoliko sekundi (svaki enkoder se testira 2 s).',
    apply_button: 'Automatski podesi',
    save_mode: 'Primijeni način',
    saved_changes: 'Spremljeno:',
    saved_nothing: 'Već je tako podešeno.',
    restart_needed: 'Ubrzanje se bira pri dizanju — treba restart servisa.',
    cpu: 'Procesor',
    threads: 'niti',
    gpu: 'Grafička / ubrzanje',
    gpu_none: 'Nema hardverskog ubrzanja',
    gpu_none_help: 'Prekodira se procesorom (više niti = brže).',
    ffmpeg_missing: 'ffmpeg nije nađen',
    burn_ok: 'titlovi (burn-in) rade',
    burn_no: 'bez `subtitles` filtra — titlovi se ne mogu urezati',
    encoder: 'Enkoder',
    kind: 'Vrsta',
    speed: 'Brzina',
    sw: 'procesor',
    fps: 'sličica/s',
    mode: 'Način rada',
    mode_auto: 'Automatski (najbrže izmjereno)',
    measured: 'izmjereno',
    mode_gpu: 'Grafička',
    mode_cpu: 'Procesor',
    mode_hybrid: 'Kombinirano (GPU dekodira, CPU enkodira)',
    recommendation: 'Preporuka',
    in_use: 'U pogonu',
    auto: 'automatski',
    hw_decode: 'hardversko dekodiranje'
  },
}

export const en = {
  app: 'Rustiio',
  nav: { dashboard: 'Overview', library: 'Library', devices: 'Devices', settings: 'Settings', logs: 'Logs' },
  field: {
    changed_unsaved: 'Changed, not saved yet',
    on: 'on',
    off: 'off',
    all_cores: 'all cores',
    cores_word: 'cores',
    all: 'All',
    auto: 'Automatic',
    unavailable: 'not available',
    absolute_hint: 'The path must start with "/"',
    browse: 'Browse folders on the server',
    add_row: 'Add row manually',
    type_path: 'Type path manually',
    tag_add: 'add…',
    root_label: 'label',
    choose: 'Browse',
    remove_root: 'Remove folder',
    add_folder: 'Add video folder',
  },
  card: {
    collapse: 'Collapsed / expanded',
    width: 'Card width',
    width_hint: 'Drag for width (or left/right arrows)',
  },
  err: {
    status: 'Could not load status',
    streams: 'Could not load streams',
    stats: 'Could not load statistics',
    devices: 'Could not load devices',
    library: 'Could not load library',
    profiles: 'Could not load profiles',
    rescan: 'Rescan failed',
    posters: 'Could not fetch posters',
    logs: 'Could not load the log',
    restart: 'Restart failed',
    server_down: 'Server is not responding — waiting for it to come back…',
    server_back: 'Server is back',
    restart_timeout: 'Service did not come back within 90 seconds — check the log',
  },
  common: {
    remove: 'Remove',
    refresh: 'Refresh',
    save: 'Save',
    saved: 'Saved',
    scan: 'Scan',
    started: 'started',
    posters: 'Posters',
    cancel: 'Cancel',
    search: 'Search',
    all: 'All',
    video: 'Video',
    audio: 'Music',
    image: 'Images',
    folder: 'Folder',
    loading: 'Loading…',
    error: 'Error',
    none: 'No data',
    copy: 'Copy',
    copied: 'Copied',
    export: 'Export',
    reset: 'Reset',
    language: 'Language',
    uptime: 'Uptime',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    days: 'd',
  },
  dashboard: {
    title: 'Overview',
    streams: 'Active streams',
    library: 'Library',
    system: 'Machine',
    disks: 'Disks',
    logs: 'Logs',
    posters: 'Posters',
    transcode: 'Transcode',
    direct: 'Direct',
    cpu: 'CPU',
    memory: 'RAM',
    gpu: 'GPU',
    load: 'Load',
    items: 'items',
    roots: 'roots',
    subscriptions: 'TVs subscribed',
    no_streams: 'Nobody is watching right now.',
    transcodes: 'transcodes',
    free: 'free',
    of: 'of',
    slots: 'free slots',
    poster_pending: 'waiting for poster',
    have_poster: 'with poster',
    no_poster: 'without poster',
    cores: 'cores',
    on: 'on',
    off: 'off',
    tmdb_key: 'TMDB key',
    no_key: 'no key',
  },
  library: {
    title: 'Library',
    search_placeholder: 'Search title…',
    empty: 'No items in this folder.',
    play: 'Play',
    copy_link: 'Copy link',
    on_tv: 'Play on TV',
    on_tv_later: 'Play on TV arrives in phase 6',
    open_folder: 'Open folder',
    items_count: 'items',
    no_poster: 'no poster',
    filter_kind: 'Kind',
    size: 'Size',
    subtitles: 'Subtitles',
    added: 'Added',
    rules: 'rules',
  },
  hw: {
    title: 'Machine it runs on',
    cpu: 'CPU',
    gpu: 'GPU',
    no_gpu: 'no hardware acceleration — transcoding runs on the CPU',
    encoders: 'Encoders',
    recommended: 'Recommended',
    subtitles_yes: 'subtitle burn-in works',
    subtitles_no: 'subtitle burn-in unavailable',
    cores: 'cores',
    threads: 'threads',
  },

  devices: {
    title: 'Devices',
    none: 'Nobody has connected yet. Turn on a TV or VLC and refresh.',
    name: 'Device',
    user_agent: 'User-Agent',
    seen: 'Last seen',
    profile: 'Profile',
    requests: 'Requests',
    headers: 'DLNA headers',
    profiles_title: 'Device profiles',
    generic: 'generic',
    dlna_client: 'DLNA client',
    hint: 'The device announces itself — it gets a profile, and you can make your own',
    make_profile: 'Create profile',
    make_profile_hint: 'Create your own profile for this device from its DLNA headers (TOML into the profiles folder)',
    toml_hint: 'Show device headers and the TOML that would be saved',
    saved: 'Profile saved',
    chosen: 'chosen',
    profile_auto: 'automatic',
    assign_hint: 'Which profile this device uses (automatic = match by User-Agent)',
    rules_title: 'Profile rules',
    rules_note: 'These rules decide whether a file plays directly or gets transcoded. Bit depth is what sends 10-bit HEVC into transcoding.',
    pick_profile: 'Profile',
    containers: 'Containers',
    video_codecs: 'Video codecs',
    audio_codecs: 'Audio codecs',
    max_width: 'Max width',
    max_height: 'Max height',
    bit_depth: 'Bit depth (bits)',
    max_bitrate: 'Max bitrate (kb/s)',
    max_channels: 'Max channels',
    target: 'Transcode into',
    target_video: 'Video codec',
    target_audio: 'Audio codec',
    target_container: 'Container',
    target_bitrate: 'Bitrate (kb/s)',
    save_rules: 'Save rules',
    saved_rules: 'Profile rules saved',
    reset_rules: 'Restore built-in',
    reset_done: 'Profile restored to built-in rules',
    list_hint: 'Comma-separated list',
    keep_small: 'Used when transcoding',
    rules_hint: 'How many profile rules match connected devices',
    delete: 'Delete',
    delete_confirm: 'Sure?',
    delete_hint: 'Deletes the profile file; devices using it fall back to automatic matching',
    deleted: 'Profile deleted',
    devices_cleared: 'devices back to automatic',
    user_profile: 'my profile',
    modified: 'modified',
    edit_profile: 'Edit rules',
    confirm_delete: 'Delete profile?',
    confirm_hint: 'The profile file is deleted. Devices that used it are left without a profile — pick another one for them afterwards.',
    delete_device: 'Delete device?',
    delete_device_hint: 'The device is removed from the list. If it shows up again, it comes back on its own.',
    device_deleted: 'Device deleted',
    device_delete_failed: 'Deleting the device failed',
    cancel: 'Cancel',
    left_without: 'devices left without a profile — pick a new one',
    no_profile: 'no profile',
    profile_name: 'Profile name',
    target_channels: 'Transcode channels',
    target_height: 'Transcode height (px)',
    target_remux: 'Allow remux (no re-encode)',
    subtitles_mode: 'Subtitles',
    subtitles_formats: 'Subtitle formats',
    sub_soft: 'Device loads them itself (soft)',
    sub_burn: 'Burn into the picture',
    sub_none: 'Device shows no subtitles',
    dlna_title: 'DLNA details',
    dlna_op: 'DLNA.ORG_OP',
    dlna_flags: 'DLNA.ORG_FLAGS',
    dlna_pn: 'Send DLNA.ORG_PN',
    dlna_time_seek: 'TimeSeekRange instead of Range',
    rules_match: 'Device matching',
    rule_ua: 'User-Agent contains',
    rule_name: 'Device name contains',
    rule_type: 'Device type',
    rule_ip: 'IP addresses',
    new_profile: 'Save as new profile',
    new_profile_ph: 'e.g. Samsung living room',
    new_needs_name: 'Type the new profile name',
    profile_created: 'New profile',
  },
  settings: {
    title: 'Settings',
    server: 'Server',
    friendly_name: 'Name on TV',
    bind: 'Address',
    port: 'Port',
    advertise_ip: 'Advertise IP',
    udn: 'UDN (identity)',
    library: 'Library',
    roots: 'Folders',
    add_root: 'Add folder',
    path: 'Path',
    label: 'Label',
    kind: 'Kind',
    transcode: 'Transcode',
    enabled: 'Enabled',
    ffmpeg: 'ffmpeg',
    ffprobe: 'ffprobe',
    max_concurrent: 'Max concurrent',
    network: 'Network',
    ip_family: 'IP family',
    ui: 'Interface',
    file: 'Config file',
    restart_needed: 'These changes need a service restart',
    restart_now: 'Restart service',
    restart_confirm: 'Active streams will be cut. Restart?',
    restarting: 'Service is coming back…',
    unchanged: 'Nothing changed',
  },
  logs: {
    title: 'Logs',
    live: 'Live',
    paused: 'Paused',
    paused_hint: 'View is frozen, lines are still collected.',
    level: 'Level',
    clear: 'Clear view',
    download: 'Download',
    connected: 'Connected',
    disconnected: 'Disconnected',
    kept: 'kept',
    filter: 'Filter',
  },
  health: { ok: 'OK', bad: 'Down' },
  // Tekstovi iz komponenti (`t('ns.kljuc')`). Isti engleski tekst = isti ključ.
  app: {
    connected: 'connected',
    every_setting_saved_to_config_toml: 'Every setting, saved to config.toml',
    live_server_log_with_levels_and_filtering: 'Live server log with levels and filtering',
    live_state_of_the_server_library_and_strea: 'Live state of the server, library and streams',
    no_log_stream: 'no log stream',
    tvs_that_appeared_and_the_profile_each_one: 'TVs that appeared, and the profile each one gets',
    what_the_tvs_see_folder_by_folder: 'What the TVs see, folder by folder',
  },
  dash: {
    acceleration: 'Acceleration',
    active_streams: 'Active streams',
    add_video_folder: 'Add video folder',
    all_devices: 'All devices',
    available_encoders: 'Available encoders',
    check_now: 'Check now',
    concurrent_limit: 'Concurrent limit',
    cores: 'cores',
    coverage: 'coverage',
    cpu: 'CPU',
    cpu_last_minutes: 'CPU — last minutes',
    devices: 'Devices',
    direct: 'Direct',
    discovery_and_subscriptions: 'Discovery and subscriptions',
    disks: 'Disks',
    folders: 'folders',
    folders_saved_a_restart_is_needed: 'Folders saved. A restart is needed.',
    folders_saved_a_restart_is_needed_reopen_t: 'Folders saved. A restart is needed: reopen the app, or restart the service on the server.',
    free: 'free',
    free_slots: 'Free slots',
    full_log: 'Full log',
    have: 'have',
    items: 'items',
    library: 'Library',
    live: 'live',
    load: 'load',
    log: 'Log',
    machine: 'Machine',
    memory: 'Memory',
    memory_last_minutes: 'Memory — last minutes',
    metadata_probed: 'Metadata probed',
    missing: 'missing',
    no_device_has_connected_yet: 'No device has connected yet.',
    no_disk_data: 'No disk data.',
    no_folder_configured: 'No folder configured.',
    no_key: 'no key',
    no_tv_is_playing_right_now: 'No TV is playing right now.',
    none: 'none',
    off: 'off',
    off_2: 'off',
    offline: 'offline',
    on: 'on',
    on_2: 'on',
    posters: 'Posters',
    remove_a_folder_that_is_gone: 'Remove a folder that is gone',
    requests: 'requests',
    reset_card_layout: 'Reset card layout',
    running_now: 'Running now',
    saving: 'saving…',
    show_listing: 'Show listing',
    subscriptions: 'subscriptions',
    the_log_is_empty: 'The log is empty.',
    titles: 'titles',
    transcode: 'Transcode',
    transcoding: 'Transcoding',
    uptime: 'Uptime',
    video: 'video',
    virtual_folders: 'Virtual folders',
    waiting: 'waiting',
  },
  set: {
    advanced: 'Advanced',
    all_saved: 'all saved',
    apply: 'Apply',
    cannot_read_settings: 'Cannot read settings',
    config_parsed_from_json_review_and_save: 'Config parsed from JSON — review and save.',
    error: 'Error',
    hide: 'Hide',
    invalid_json: 'Invalid JSON',
    not_saved: 'Not saved',
    restart_pending: 'restart pending',
    restart_pending_2: 'restart pending',
    restart_service: 'Restart service',
    restart_the_service_now_streams_will_drop: 'Restart the service now? Streams will drop.',
    revert: 'Revert',
    save_settings: 'Save settings',
    saving: 'Saving…',
    service_is_coming_back_page_will_reload: 'Service is coming back… page will reload.',
    settings_sections: 'Settings sections',
    show: 'Show',
    some_fields_apply_only_after_a_service_res: 'Some fields apply only after a service restart.',
    the_whole_config_as_json_use_it_for_anythi: 'The whole config as JSON. Use it for anything not in the form — and to copy settings to another server.',
    these_fields_are_saved_but_take_effect_onl: 'These fields are saved but take effect only after a restart:',
  },
  side: {
    items: 'items',
    live_log_connected: 'live log connected',
    log_disconnected: 'log disconnected',
  },
  tr: {
    scan_title: 'System scan and automatic setup',
    scan_help: 'Check what the machine has (ffmpeg, CPU, GPU) and measure the real speed of every encoder. The recommendation is based on measurement, not assumptions.',
    scan_button: 'Scan the system',
    scanning: 'Scanning…',
    scan_hint: 'Press “Scan the system” — it takes a few seconds (each encoder is tested for 2 s).',
    apply_button: 'Set up automatically',
    save_mode: 'Apply the mode',
    saved_changes: 'Saved:',
    saved_nothing: 'Already set that way.',
    restart_needed: 'Acceleration is chosen at startup — the service needs a restart.',
    cpu: 'CPU',
    threads: 'threads',
    gpu: 'GPU / acceleration',
    gpu_none: 'No hardware acceleration',
    gpu_none_help: 'Encoding runs on the CPU (more threads = faster).',
    ffmpeg_missing: 'ffmpeg not found',
    burn_ok: 'subtitles (burn-in) available',
    burn_no: 'no `subtitles` filter — burn-in is not possible',
    encoder: 'Encoder',
    kind: 'Kind',
    speed: 'Speed',
    sw: 'CPU',
    fps: 'frames/s',
    mode: 'Mode',
    mode_auto: 'Automatic (fastest measured)',
    measured: 'measured',
    mode_gpu: 'GPU',
    mode_cpu: 'CPU',
    mode_hybrid: 'Hybrid (GPU decodes, CPU encodes)',
    recommendation: 'Recommendation',
    in_use: 'In use',
    auto: 'automatic',
    hw_decode: 'hardware decoding'
  },
}

export const dictionaries = { hr, en }
