// Prijevodi (hr/en) — samo podaci, bez stanja.
//
// Zašto odvojeno od `i18n.svelte.js`: rune (`$state`) se ne mogu uvesti u Node,
// a ovako `scripts/check-i18n.mjs` provjerava da oba jezika imaju iste ključeve.

export const hr = {
  app: 'Rustiio',
  nav: { dashboard: 'Pregled', library: 'Knjižnica', devices: 'Uređaji', settings: 'Postavke', logs: 'Zapisnik' },
  common: {
    refresh: 'Osvježi',
    save: 'Spremi',
    saved: 'Spremljeno',
    cancel: 'Odustani',
    search: 'Traži',
    all: 'Sve',
    video: 'Video',
    audio: 'Glazba',
    image: 'Slike',
    folder: 'Mapa',
    loading: 'Učitavam…',
    error: 'Greška',
    none: 'Nema podataka',
    copy: 'Kopiraj',
    copied: 'Kopirano',
    export: 'Izvezi',
    reset: 'Vrati početno',
    language: 'Jezik',
    uptime: 'Radi',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    days: 'd',
  },
  dashboard: {
    title: 'Pregled',
    streams: 'Aktivni streamovi',
    library: 'Knjižnica',
    system: 'Računalo',
    disks: 'Diskovi',
    logs: 'Zapisnik',
    posters: 'Posteri',
    transcode: 'Transcode',
    direct: 'Izravno',
    cpu: 'CPU',
    memory: 'RAM',
    gpu: 'GPU',
    load: 'Opterećenje',
    items: 'objekata',
    roots: 'mapa',
    subscriptions: 'TV-a pretplaćeno',
    no_streams: 'Nitko trenutno ne gleda.',
    transcodes: 'transcode',
    free: 'slobodno',
    of: 'od',
    slots: 'slobodnih mjesta',
    poster_pending: 'čeka poster',
    have_poster: 'imaju poster',
    no_poster: 'bez postera',
    cores: 'jezgre',
    on: 'uključen',
    off: 'isključen',
    tmdb_key: 'TMDB ključ',
    no_key: 'bez ključa',
  },
  library: {
    title: 'Knjižnica',
    search_placeholder: 'Traži naslov…',
    empty: 'Nema objekata u ovoj mapi.',
    play: 'Pusti',
    copy_link: 'Kopiraj link',
    on_tv: 'Pusti na TV',
    on_tv_later: 'Pusti na TV dolazi u Fazi 6',
    open_folder: 'Otvori mapu',
    items_count: 'objekata',
    no_poster: 'bez postera',
    filter_kind: 'Vrsta',
    size: 'Veličina',
    added: 'Dodano',
    rules: 'pravila',
  },
  devices: {
    title: 'Uređaji',
    none: 'Još se nitko nije javio. Uključi TV ili VLC i osvježi.',
    name: 'Uređaj',
    user_agent: 'User-Agent',
    seen: 'Zadnji put',
    profile: 'Profil',
    requests: 'Zahtjeva',
    headers: 'DLNA zaglavlja',
    profiles_title: 'Profili uređaja',
    generic: 'općenito',
  },
  settings: {
    title: 'Postavke',
    server: 'Server',
    friendly_name: 'Ime na TV-u',
    bind: 'Adresa',
    port: 'Port',
    advertise_ip: 'IP za oglašavanje',
    udn: 'UDN (identitet)',
    library: 'Biblioteka',
    roots: 'Mape',
    add_root: 'Dodaj mapu',
    path: 'Putanja',
    label: 'Naziv',
    kind: 'Vrsta',
    transcode: 'Transcode',
    enabled: 'Uključen',
    ffmpeg: 'ffmpeg',
    ffprobe: 'ffprobe',
    max_concurrent: 'Najviše paralelno',
    network: 'Mreža',
    ip_family: 'Obitelj IP-a',
    ui: 'Sučelje',
    file: 'Datoteka configa',
    restart_needed: 'Za ove promjene treba restart servisa',
    restart_now: 'Restartaj servis',
    restart_confirm: 'Prekinut će se aktivni streamovi. Restartati?',
    restarting: 'Servis se diže…',
    unchanged: 'Nema promjena',
  },
  logs: {
    title: 'Zapisnik',
    live: 'Živo',
    paused: 'Pauzirano',
    paused_hint: 'Prikaz je zaustavljen, linije se i dalje skupljaju.',
    level: 'Razina',
    clear: 'Očisti prikaz',
    download: 'Preuzmi',
    connected: 'Spojen',
    disconnected: 'Veza prekinuta',
    kept: 'zadržano',
    filter: 'Filtar',
  },
  health: { ok: 'Radi', bad: 'Ne radi' },
  // Tekstovi iz komponenti (`t('ns.kljuc')`). Isti engleski tekst = isti ključ.
  app: {
    connected: 'spojeno',
    every_setting_saved_to_config_toml: 'Sva podešavanja, spremaju se u config.toml',
    live_server_log_with_levels_and_filtering: 'Zapisnik servera u živo, s razinama i filtriranjem',
    live_state_of_the_server_library_and_strea: 'Stanje servera, knjižnice i strimova u živo',
    no_log_stream: 'nema toka',
    tvs_that_appeared_and_the_profile_each_one: 'Televizori koji su se pojavili i profil koji svaki dobiva',
    what_the_tvs_see_folder_by_folder: 'Ono što televizori vide, mapa po mapa',
  },
  dash: {
    acceleration: 'Ubrzanje',
    active_streams: 'Aktivni strimovi',
    add_video_folder: 'Dodaj mapu s videom',
    all_devices: 'Svi uređaji',
    available_encoders: 'Dostupni enkoderi',
    check_now: 'Provjeri sada',
    concurrent_limit: 'Istovremeno najviše',
    cores: 'jezgre',
    coverage: 'pokrivenosti',
    cpu: 'Procesor',
    cpu_last_minutes: 'Procesor — zadnjih minuta',
    devices: 'Uređaji',
    direct: 'Izravno',
    discovery_and_subscriptions: 'Oglasi i pretplate',
    disks: 'Diskovi',
    folders: 'mapa',
    folders_saved_a_restart_is_needed: 'Mape spremljene. Za promjenu treba ponovno pokretanje.',
    folders_saved_a_restart_is_needed_reopen_t: 'Mape spremljene. Za novu mapu treba ponovno pokretanje: u aplikaciji zatvori i otvori Rustiio, na serveru restartaj uslugu.',
    free: 'slobodno',
    free_slots: 'Slobodnih mjesta',
    full_log: 'Cijeli zapisnik',
    have: 'imaju',
    items: 'objekata',
    library: 'Knjižnica',
    live: 'uživo',
    load: 'opterećenje',
    log: 'Zapisnik',
    machine: 'Računalo',
    memory: 'Memorija',
    memory_last_minutes: 'Memorija — zadnjih minuta',
    metadata_probed: 'Metapodaci izmjereni',
    missing: 'nema mape',
    no_device_has_connected_yet: 'Još se nijedan uređaj nije javio.',
    no_disk_data: 'Nema podataka o diskovima.',
    no_folder_configured: 'Nijedna mapa nije zadana.',
    no_key: 'bez ključa',
    no_tv_is_playing_right_now: 'Nijedan televizor trenutačno ne gleda.',
    none: 'nema',
    off: 'isključene',
    off_2: 'isključeno',
    offline: 'prekinuto',
    on: 'uključene',
    on_2: 'uključeno',
    posters: 'Naslovnice',
    remove_a_folder_that_is_gone: 'Ukloni mapu koje nema na disku',
    requests: 'zahtjeva',
    reset_card_layout: 'Vrati raspored kartica',
    running_now: 'U tijeku',
    saving: 'spremam…',
    show_listing: 'Prikaži popis',
    subscriptions: 'pretplata',
    the_log_is_empty: 'Zapisnik je prazan.',
    titles: 'naslova',
    transcode: 'Prekodira',
    transcoding: 'Prekodiranje',
    uptime: 'Radi neprekidno',
    video: 'video',
    virtual_folders: 'Virtualne mape',
    waiting: 'čeka',
  },
  set: {
    advanced: 'Napredno',
    all_saved: 'sve spremljeno',
    apply: 'Primijeni',
    cannot_read_settings: 'Ne mogu pročitati postavke',
    config_parsed_from_json_review_and_save: 'Config pročitan iz JSON-a — provjeri i spremi.',
    error: 'Greška',
    hide: 'Sakrij',
    invalid_json: 'JSON nije ispravan',
    not_saved: 'Nije spremljeno',
    restart_pending: 'čeka restart',
    restart_pending_2: 'restart čeka',
    restart_service: 'Restartaj servis',
    restart_the_service_now_streams_will_drop: 'Restartati servis sada? Strimovi će se prekinuti.',
    revert: 'Vrati',
    save_settings: 'Spremi postavke',
    saving: 'Spremam…',
    service_is_coming_back_page_will_reload: 'Servis se diže… stranica će se osvježiti.',
    settings_sections: 'Sekcije postavki',
    show: 'Prikaži',
    some_fields_apply_only_after_a_service_res: 'Neka polja vrijede tek nakon restarta servisa.',
    the_whole_config_as_json_use_it_for_anythi: 'Cijeli config kao JSON. Koristi kad nešto nije u obrascu — i za kopiranje postavki na drugi server.',
    these_fields_are_saved_but_take_effect_onl: 'Ova polja su spremljena, ali vrijede tek kad se servis digne:',
  },
  side: {
    items: 'stavki',
    live_log_connected: 'živi zapisnik spojen',
    log_disconnected: 'zapisnik nije spojen',
  },
}

export const en = {
  app: 'Rustiio',
  nav: { dashboard: 'Overview', library: 'Library', devices: 'Devices', settings: 'Settings', logs: 'Logs' },
  common: {
    refresh: 'Refresh',
    save: 'Save',
    saved: 'Saved',
    cancel: 'Cancel',
    search: 'Search',
    all: 'All',
    video: 'Video',
    audio: 'Music',
    image: 'Images',
    folder: 'Folder',
    loading: 'Loading…',
    error: 'Error',
    none: 'No data',
    copy: 'Copy',
    copied: 'Copied',
    export: 'Export',
    reset: 'Reset',
    language: 'Language',
    uptime: 'Uptime',
    seconds: 's',
    minutes: 'min',
    hours: 'h',
    days: 'd',
  },
  dashboard: {
    title: 'Overview',
    streams: 'Active streams',
    library: 'Library',
    system: 'Machine',
    disks: 'Disks',
    logs: 'Logs',
    posters: 'Posters',
    transcode: 'Transcode',
    direct: 'Direct',
    cpu: 'CPU',
    memory: 'RAM',
    gpu: 'GPU',
    load: 'Load',
    items: 'items',
    roots: 'roots',
    subscriptions: 'TVs subscribed',
    no_streams: 'Nobody is watching right now.',
    transcodes: 'transcodes',
    free: 'free',
    of: 'of',
    slots: 'free slots',
    poster_pending: 'waiting for poster',
    have_poster: 'with poster',
    no_poster: 'without poster',
    cores: 'cores',
    on: 'on',
    off: 'off',
    tmdb_key: 'TMDB key',
    no_key: 'no key',
  },
  library: {
    title: 'Library',
    search_placeholder: 'Search title…',
    empty: 'No items in this folder.',
    play: 'Play',
    copy_link: 'Copy link',
    on_tv: 'Play on TV',
    on_tv_later: 'Play on TV arrives in phase 6',
    open_folder: 'Open folder',
    items_count: 'items',
    no_poster: 'no poster',
    filter_kind: 'Kind',
    size: 'Size',
    added: 'Added',
    rules: 'rules',
  },
  devices: {
    title: 'Devices',
    none: 'Nobody has connected yet. Turn on a TV or VLC and refresh.',
    name: 'Device',
    user_agent: 'User-Agent',
    seen: 'Last seen',
    profile: 'Profile',
    requests: 'Requests',
    headers: 'DLNA headers',
    profiles_title: 'Device profiles',
    generic: 'generic',
  },
  settings: {
    title: 'Settings',
    server: 'Server',
    friendly_name: 'Name on TV',
    bind: 'Address',
    port: 'Port',
    advertise_ip: 'Advertise IP',
    udn: 'UDN (identity)',
    library: 'Library',
    roots: 'Folders',
    add_root: 'Add folder',
    path: 'Path',
    label: 'Label',
    kind: 'Kind',
    transcode: 'Transcode',
    enabled: 'Enabled',
    ffmpeg: 'ffmpeg',
    ffprobe: 'ffprobe',
    max_concurrent: 'Max concurrent',
    network: 'Network',
    ip_family: 'IP family',
    ui: 'Interface',
    file: 'Config file',
    restart_needed: 'These changes need a service restart',
    restart_now: 'Restart service',
    restart_confirm: 'Active streams will be cut. Restart?',
    restarting: 'Service is coming back…',
    unchanged: 'Nothing changed',
  },
  logs: {
    title: 'Logs',
    live: 'Live',
    paused: 'Paused',
    paused_hint: 'View is frozen, lines are still collected.',
    level: 'Level',
    clear: 'Clear view',
    download: 'Download',
    connected: 'Connected',
    disconnected: 'Disconnected',
    kept: 'kept',
    filter: 'Filter',
  },
  health: { ok: 'OK', bad: 'Down' },
  // Tekstovi iz komponenti (`t('ns.kljuc')`). Isti engleski tekst = isti ključ.
  app: {
    connected: 'connected',
    every_setting_saved_to_config_toml: 'Every setting, saved to config.toml',
    live_server_log_with_levels_and_filtering: 'Live server log with levels and filtering',
    live_state_of_the_server_library_and_strea: 'Live state of the server, library and streams',
    no_log_stream: 'no log stream',
    tvs_that_appeared_and_the_profile_each_one: 'TVs that appeared, and the profile each one gets',
    what_the_tvs_see_folder_by_folder: 'What the TVs see, folder by folder',
  },
  dash: {
    acceleration: 'Acceleration',
    active_streams: 'Active streams',
    add_video_folder: 'Add video folder',
    all_devices: 'All devices',
    available_encoders: 'Available encoders',
    check_now: 'Check now',
    concurrent_limit: 'Concurrent limit',
    cores: 'cores',
    coverage: 'coverage',
    cpu: 'CPU',
    cpu_last_minutes: 'CPU — last minutes',
    devices: 'Devices',
    direct: 'Direct',
    discovery_and_subscriptions: 'Discovery and subscriptions',
    disks: 'Disks',
    folders: 'folders',
    folders_saved_a_restart_is_needed: 'Folders saved. A restart is needed.',
    folders_saved_a_restart_is_needed_reopen_t: 'Folders saved. A restart is needed: reopen the app, or restart the service on the server.',
    free: 'free',
    free_slots: 'Free slots',
    full_log: 'Full log',
    have: 'have',
    items: 'items',
    library: 'Library',
    live: 'live',
    load: 'load',
    log: 'Log',
    machine: 'Machine',
    memory: 'Memory',
    memory_last_minutes: 'Memory — last minutes',
    metadata_probed: 'Metadata probed',
    missing: 'missing',
    no_device_has_connected_yet: 'No device has connected yet.',
    no_disk_data: 'No disk data.',
    no_folder_configured: 'No folder configured.',
    no_key: 'no key',
    no_tv_is_playing_right_now: 'No TV is playing right now.',
    none: 'none',
    off: 'off',
    off_2: 'off',
    offline: 'offline',
    on: 'on',
    on_2: 'on',
    posters: 'Posters',
    remove_a_folder_that_is_gone: 'Remove a folder that is gone',
    requests: 'requests',
    reset_card_layout: 'Reset card layout',
    running_now: 'Running now',
    saving: 'saving…',
    show_listing: 'Show listing',
    subscriptions: 'subscriptions',
    the_log_is_empty: 'The log is empty.',
    titles: 'titles',
    transcode: 'Transcode',
    transcoding: 'Transcoding',
    uptime: 'Uptime',
    video: 'video',
    virtual_folders: 'Virtual folders',
    waiting: 'waiting',
  },
  set: {
    advanced: 'Advanced',
    all_saved: 'all saved',
    apply: 'Apply',
    cannot_read_settings: 'Cannot read settings',
    config_parsed_from_json_review_and_save: 'Config parsed from JSON — review and save.',
    error: 'Error',
    hide: 'Hide',
    invalid_json: 'Invalid JSON',
    not_saved: 'Not saved',
    restart_pending: 'restart pending',
    restart_pending_2: 'restart pending',
    restart_service: 'Restart service',
    restart_the_service_now_streams_will_drop: 'Restart the service now? Streams will drop.',
    revert: 'Revert',
    save_settings: 'Save settings',
    saving: 'Saving…',
    service_is_coming_back_page_will_reload: 'Service is coming back… page will reload.',
    settings_sections: 'Settings sections',
    show: 'Show',
    some_fields_apply_only_after_a_service_res: 'Some fields apply only after a service restart.',
    the_whole_config_as_json_use_it_for_anythi: 'The whole config as JSON. Use it for anything not in the form — and to copy settings to another server.',
    these_fields_are_saved_but_take_effect_onl: 'These fields are saved but take effect only after a restart:',
  },
  side: {
    items: 'items',
    live_log_connected: 'live log connected',
    log_disconnected: 'log disconnected',
  },
}

export const dictionaries = { hr, en }
