[package]
name = "rustiio-server"
description = "Orkestracija: axum router, state i REST API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rustiio-core.workspace = true
rustiio-cds.workspace = true
rustiio-http.workspace = true
rustiio-library.workspace = true
rustiio-profiles.workspace = true
rustiio-ssdp.workspace = true
rustiio-transcode.workspace = true
rustiio-upnp.workspace = true
anyhow.workspace = true
axum = { workspace = true, features = ["ws"] }
futures-core.workspace = true
tower-http.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
sysinfo = "0.36.1"
rust-embed = "8.12.0"
mime_guess = "2.0.5"
serde = { workspace = true, features = ["derive"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
